# Generated by Django 5.0.1 on 2026-02-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("team_lead", "Team Lead"),
                    ("staff", "Staff"),
                    ("freelancer", "Freelancer"),
                ],
                default="freelancer",
                help_text="Vai trò của người dùng trong hệ thống",
                max_length=20,
            ),
        ),
    ]
