# Generated by Django 5.0.1 on 2026-03-10 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Event title", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Event description"),
                ),
                ("start_date", models.DateField(help_text="Event start date")),
                ("end_date", models.DateField(help_text="Event end date")),
                (
                    "start_time",
                    models.TimeField(
                        blank=True, help_text="Event start time (optional)", null=True
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        blank=True, help_text="Event end time (optional)", null=True
                    ),
                ),
                (
                    "is_all_day",
                    models.BooleanField(
                        default=True, help_text="Is this an all-day event"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3b82f6",
                        help_text="Event color (hex format)",
                        max_length=7,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Event owner",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["start_date", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["user", "start_date"],
                        name="events_even_user_id_013578_idx",
                    ),
                    models.Index(
                        fields=["start_date", "end_date"],
                        name="events_even_start_d_7e0d92_idx",
                    ),
                ],
            },
        ),
    ]
