# Generated by Django 5.0.1 on 2026-02-03 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("task_assigned", "Task Assigned"),
                            ("task_status_changed", "Task Status Changed"),
                            ("new_comment", "New Comment"),
                            ("review_completed", "Review Completed"),
                            ("file_uploaded", "File Uploaded"),
                            ("task_due_soon", "Task Due Soon"),
                            ("task_overdue", "Task Overdue"),
                        ],
                        help_text="Loại thông báo",
                        max_length=50,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Tiêu đề thông báo", max_length=200),
                ),
                ("message", models.TextField(help_text="Nội dung thông báo")),
                (
                    "is_read",
                    models.BooleanField(default=False, help_text="Đã đọc hay chưa"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="Người nhận thông báo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        help_text="Task liên quan (nếu có)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
