# Generated by Django 5.0.1 on 2026-02-03 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Tên dự án", max_length=200)),
                ("description", models.TextField(blank=True, help_text="Mô tả dự án")),
                (
                    "client_name",
                    models.CharField(
                        blank=True, help_text="Tên khách hàng", max_length=200
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, help_text="Ngày bắt đầu", null=True),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, help_text="Ngày kết thúc", null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        help_text="Trạng thái dự án",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Người tạo dự án",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DesignRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Tên quy tắc", max_length=200)),
                ("description", models.TextField(help_text="Mô tả chi tiết quy tắc")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("layout", "Layout"),
                            ("typography", "Typography"),
                            ("color", "Color Scheme"),
                            ("content", "Content"),
                            ("animation", "Animation"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Danh mục quy tắc",
                        max_length=50,
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True, help_text="Quy tắc bắt buộc hay tùy chọn"
                    ),
                ),
                ("order", models.IntegerField(default=0, help_text="Thứ tự sắp xếp")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Dự án áp dụng quy tắc này",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_rules",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Design Rule",
                "verbose_name_plural": "Design Rules",
                "ordering": ["project", "order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Tên chủ đề", max_length=200)),
                ("description", models.TextField(blank=True, help_text="Mô tả chủ đề")),
                ("order", models.IntegerField(default=0, help_text="Thứ tự sắp xếp")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Dự án chứa chủ đề này",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Topic",
                "verbose_name_plural": "Topics",
                "ordering": ["project", "order", "created_at"],
                "unique_together": {("project", "name")},
            },
        ),
    ]
