# Generated by Django 5.0.1 on 2026-02-28 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Khách hàng của dự án', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='crm.customer'),
        ),
    ]
