# Generated by Django 5.0.1 on 2026-03-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_project_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="budget",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Ngân sách dự án (VND)",
                max_digits=12,
                null=True,
            ),
        ),
    ]
