# Generated by Django 5.0.1 on 2026-03-16 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_project_departments_members"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Tên stage", max_length=100)),
                ("description", models.TextField(blank=True, help_text="Mô tả stage")),
                ("order", models.IntegerField(default=0, help_text="Thứ tự sắp xếp")),
                (
                    "color",
                    models.CharField(
                        default="gray",
                        help_text="Màu hiển thị (gray, blue, purple, orange, yellow, green, red)",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Dự án chứa stage này",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Stage",
                "verbose_name_plural": "Project Stages",
                "ordering": ["project", "order", "created_at"],
                "unique_together": {("project", "name")},
            },
        ),
    ]
