# Generated by Django 5.0.1 on 2026-02-04 06:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CareerPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("junior", "Junior"),
                            ("mid", "Mid-Level"),
                            ("senior", "Senior"),
                            ("lead", "Team Lead"),
                            ("manager", "Manager"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "min_years_experience",
                    models.IntegerField(
                        help_text="Số năm kinh nghiệm tối thiểu",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "min_salary",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Mức lương tối thiểu",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_salary",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Mức lương tối đa",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "requirements",
                    models.TextField(help_text="Yêu cầu kỹ năng và trách nhiệm"),
                ),
                (
                    "benefits",
                    models.TextField(blank=True, help_text="Quyền lợi đi kèm"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Career Path",
                "verbose_name_plural": "Career Paths",
                "ordering": ["min_years_experience"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_departments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        help_text="Mã nhân viên", max_length=20, unique=True
                    ),
                ),
                ("position", models.CharField(help_text="Chức vụ", max_length=100)),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("fulltime", "Full-time"),
                            ("parttime", "Part-time"),
                            ("contract", "Contract"),
                        ],
                        default="fulltime",
                        max_length=20,
                    ),
                ),
                ("join_date", models.DateField(help_text="Ngày vào công ty")),
                (
                    "current_salary",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("last_salary_review", models.DateField(blank=True, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "citizen_id",
                    models.CharField(blank=True, help_text="CCCD/CMND", max_length=20),
                ),
                ("address", models.TextField(blank=True)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=20),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "career_level",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="hr.careerpath",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="hr.department",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={
                            "role__in": ["admin", "manager", "team_lead", "staff"]
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-join_date"],
            },
        ),
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "overall_rating",
                    models.CharField(
                        choices=[
                            ("outstanding", "Outstanding"),
                            ("exceeds", "Exceeds Expectations"),
                            ("meets", "Meets Expectations"),
                            ("needs_improvement", "Needs Improvement"),
                            ("unsatisfactory", "Unsatisfactory"),
                        ],
                        max_length=20,
                    ),
                ),
                ("strengths", models.TextField(help_text="Điểm mạnh")),
                (
                    "areas_for_improvement",
                    models.TextField(help_text="Điểm cần cải thiện"),
                ),
                ("achievements", models.TextField(help_text="Thành tích nổi bật")),
                (
                    "goals_next_period",
                    models.TextField(help_text="Mục tiêu kỳ tiếp theo"),
                ),
                (
                    "promotion_recommended",
                    models.BooleanField(default=False, help_text="Đề xuất thăng chức"),
                ),
                (
                    "salary_increase_recommended",
                    models.BooleanField(default=False, help_text="Đề xuất tăng lương"),
                ),
                (
                    "recommended_increase_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Phần trăm tăng lương đề xuất",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "employee_comments",
                    models.TextField(blank=True, help_text="Ý kiến của nhân viên"),
                ),
                (
                    "employee_acknowledged",
                    models.BooleanField(
                        default=False, help_text="Nhân viên đã xác nhận"
                    ),
                ),
                (
                    "employee_acknowledged_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="hr.employee",
                    ),
                ),
                (
                    "evaluator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conducted_evaluations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-period_end"],
            },
        ),
        migrations.CreateModel(
            name="SalaryReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_salary",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "proposed_salary",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "increase_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("reason", models.TextField(help_text="Lý do đề xuất tăng lương")),
                (
                    "justification",
                    models.TextField(
                        blank=True, help_text="Căn cứ: KPI, đánh giá, thành tích"
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(help_text="Ngày bắt đầu áp dụng mức lương mới"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("implemented", "Implemented"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_reviews",
                        to="hr.employee",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_salary_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_salary_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.DateField(help_text="Tháng đánh giá (chỉ lưu năm-tháng)"),
                ),
                (
                    "tasks_completed",
                    models.IntegerField(
                        default=0,
                        help_text="Số task hoàn thành",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "tasks_on_time",
                    models.IntegerField(
                        default=0,
                        help_text="Số task hoàn thành đúng hạn",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "quality_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Điểm chất lượng (0-10)",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "collaboration_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Điểm làm việc nhóm (0-10)",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "innovation_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Điểm sáng tạo (0-10)",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "overall_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Điểm tổng hợp (0-10)",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_kpis",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpis",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "KPI",
                "verbose_name_plural": "KPIs",
                "ordering": ["-month"],
                "unique_together": {("employee", "month")},
            },
        ),
        migrations.CreateModel(
            name="PersonalReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[("weekly", "Weekly"), ("monthly", "Monthly")],
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("summary", models.TextField(help_text="Tóm tắt công việc đã làm")),
                ("achievements", models.TextField(help_text="Thành tích đạt được")),
                (
                    "challenges",
                    models.TextField(blank=True, help_text="Khó khăn gặp phải"),
                ),
                (
                    "plan_next_period",
                    models.TextField(blank=True, help_text="Kế hoạch kỳ tiếp theo"),
                ),
                (
                    "tasks_completed",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "hours_worked",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("manager_feedback", models.TextField(blank=True)),
                ("manager_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="hr.employee",
                    ),
                ),
                (
                    "manager_reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-period_end"],
                "unique_together": {("employee", "report_type", "period_start")},
            },
        ),
    ]
