# Generated by Django 5.0.1 on 2026-03-02 10:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0002_plan_plangoal_plannote_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="plan_type",
            field=models.CharField(
                choices=[
                    ("daily", "Daily Plan"),
                    ("weekly", "Weekly Plan"),
                    ("monthly", "Monthly Plan"),
                    ("quarterly", "Quarterly Plan"),
                    ("yearly", "Yearly Plan"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PlanDailyProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Date of progress entry")),
                (
                    "completed_goals_count",
                    models.IntegerField(
                        default=0,
                        help_text="Goals completed on this day",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "hours_worked",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Hours spent on plan this day",
                        max_digits=4,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "progress_notes",
                    models.TextField(
                        blank=True, help_text="Notes about today's progress"
                    ),
                ),
                (
                    "completion_percentage_snapshot",
                    models.IntegerField(
                        default=0,
                        help_text="Plan completion % at end of day",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_progress",
                        to="hr.plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan Daily Progress",
                "verbose_name_plural": "Plan Daily Progress Entries",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["plan", "-date"], name="hr_plandail_plan_id_0da678_idx"
                    )
                ],
                "unique_together": {("plan", "date")},
            },
        ),
        migrations.CreateModel(
            name="PlanUpdateHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("status_changed", "Status Changed"),
                            ("goal_added", "Goal Added"),
                            ("goal_completed", "Goal Completed"),
                            ("reviewed", "Reviewed by Manager"),
                        ],
                        max_length=20,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "previous_values",
                    models.JSONField(
                        blank=True, help_text="Previous state before change", null=True
                    ),
                ),
                (
                    "current_values",
                    models.JSONField(
                        blank=True, help_text="New state after change", null=True
                    ),
                ),
                (
                    "change_description",
                    models.TextField(
                        blank=True, help_text="Human-readable description of change"
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plan_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="update_history",
                        to="hr.plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan Update History",
                "verbose_name_plural": "Plan Update Histories",
                "ordering": ["-changed_at"],
                "indexes": [
                    models.Index(
                        fields=["plan", "-changed_at"],
                        name="hr_planupda_plan_id_8fac16_idx",
                    )
                ],
            },
        ),
    ]
