# Generated by Django 5.0.1 on 2026-03-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0003_alter_plan_plan_type_plandailyprogress_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plandailyprogress",
            name="blockers",
            field=models.TextField(blank=True, help_text="Issues/blockers encountered today"),
        ),
        migrations.AddField(
            model_name="plandailyprogress",
            name="next_plan",
            field=models.TextField(blank=True, help_text="Next steps planned for upcoming work"),
        ),
        migrations.AddField(
            model_name="plandailyprogress",
            name="work_results",
            field=models.TextField(blank=True, help_text="Key outcomes/deliverables completed today"),
        ),
    ]
