# Generated by Django 5.0.1 on 2026-03-04 06:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0004_plandailyprogress_work_summary_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work_start_time",
                    models.TimeField(
                        default="09:00", help_text="Standard work start time"
                    ),
                ),
                (
                    "work_end_time",
                    models.TimeField(
                        default="18:00", help_text="Standard work end time"
                    ),
                ),
                (
                    "late_threshold_minutes",
                    models.IntegerField(
                        default=15,
                        help_text="Minutes after start time to mark as late",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "require_checkout",
                    models.BooleanField(
                        default=True,
                        help_text="Require users to check out at end of day",
                    ),
                ),
                (
                    "allow_remote_checkin",
                    models.BooleanField(
                        default=True, help_text="Allow check-in from remote locations"
                    ),
                ),
                (
                    "send_reminder_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="Send notifications to remind check-in/out",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Attendance Settings",
                "verbose_name_plural": "Attendance Settings",
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Date of attendance")),
                (
                    "check_in_time",
                    models.DateTimeField(
                        blank=True, help_text="Time when user checked in", null=True
                    ),
                ),
                (
                    "check_out_time",
                    models.DateTimeField(
                        blank=True, help_text="Time when user checked out", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("half_day", "Half Day"),
                            ("wfh", "Work From Home"),
                        ],
                        default="present",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes (e.g., reason for late, WFH details)",
                    ),
                ),
                (
                    "check_in_location",
                    models.CharField(
                        blank=True,
                        help_text="Location when checked in (e.g., Office, Home)",
                        max_length=200,
                    ),
                ),
                (
                    "check_out_location",
                    models.CharField(
                        blank=True,
                        help_text="Location when checked out",
                        max_length=200,
                    ),
                ),
                (
                    "total_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total hours worked (auto-calculated)",
                        max_digits=4,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "is_late",
                    models.BooleanField(
                        default=False,
                        help_text="Marked as late if check-in after configured time",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who checked in",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance",
                "verbose_name_plural": "Attendances",
                "ordering": ["-date", "-check_in_time"],
                "indexes": [
                    models.Index(
                        fields=["user", "-date"], name="hr_attendan_user_id_fc7e65_idx"
                    ),
                    models.Index(fields=["date"], name="hr_attendan_date_3a46d7_idx"),
                ],
                "unique_together": {("user", "date")},
            },
        ),
    ]
