# Generated by Django 5.0.1 on 2026-03-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0005_attendancesettings_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="check_in_accuracy",
            field=models.FloatField(
                blank=True, help_text="GPS accuracy in meters at check-in", null=True
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_in_address",
            field=models.CharField(
                blank=True,
                help_text="Reverse geocoded address at check-in",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_in_device_browser",
            field=models.CharField(
                blank=True,
                help_text="Browser (e.g., Chrome, Firefox, Safari)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_in_device_os",
            field=models.CharField(
                blank=True,
                help_text="Operating system (e.g., Windows, macOS, Android)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_in_device_type",
            field=models.CharField(
                blank=True,
                help_text="Device type: Desktop, Mobile, Tablet",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_in_ip",
            field=models.GenericIPAddressField(
                blank=True, help_text="IP address at check-in", null=True
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_in_latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="GPS latitude at check-in",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_in_longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="GPS longitude at check-in",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_in_user_agent",
            field=models.TextField(blank=True, help_text="Full user agent string"),
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_out_accuracy",
            field=models.FloatField(
                blank=True, help_text="GPS accuracy in meters at check-out", null=True
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_out_address",
            field=models.CharField(
                blank=True,
                help_text="Reverse geocoded address at check-out",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_out_device_browser",
            field=models.CharField(
                blank=True,
                help_text="Browser (e.g., Chrome, Firefox, Safari)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_out_device_os",
            field=models.CharField(
                blank=True,
                help_text="Operating system (e.g., Windows, macOS, Android)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_out_device_type",
            field=models.CharField(
                blank=True,
                help_text="Device type: Desktop, Mobile, Tablet",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_out_ip",
            field=models.GenericIPAddressField(
                blank=True, help_text="IP address at check-out", null=True
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_out_latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="GPS latitude at check-out",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_out_longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="GPS longitude at check-out",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_out_user_agent",
            field=models.TextField(blank=True, help_text="Full user agent string"),
        ),
    ]
