# Generated by Django 5.0.1 on 2026-03-05 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0006_add_attendance_metadata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                help_text="Direct manager or team lead",
                limit_choices_to={"role__in": ["admin", "manager", "team_lead"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_employees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
