# Generated by Django 5.0.1 on 2026-02-03 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Tiêu đề task", max_length=200)),
                ("description", models.TextField(help_text="Mô tả chi tiết task")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("assigned", "Assigned"),
                            ("working", "Working"),
                            ("review_pending", "Review Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed"),
                        ],
                        default="new",
                        help_text="Trạng thái task",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        help_text="Độ ưu tiên",
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Giá tiền cho task này",
                        max_digits=10,
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True, help_text="Hạn chót hoàn thành", null=True
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="Thời gian bắt đầu làm", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="Thời gian hoàn thành", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Người giao task (Manager/Admin)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Freelancer được giao task",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "design_rules",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Các quy tắc thiết kế áp dụng cho task này",
                        related_name="tasks",
                        to="projects.designrule",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Dự án chứa task này",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="projects.project",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        help_text="Chủ đề của task",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="projects.topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(help_text="Nội dung comment")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Comment cha (nếu là reply)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="tasks.taskcomment",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        help_text="Task chứa comment này",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="tasks.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Người comment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Comment",
                "verbose_name_plural": "Task Comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="File đính kèm", upload_to="task_files/"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("reference", "Reference"),
                            ("submission", "Submission"),
                            ("revision", "Revision"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Loại file",
                        max_length=20,
                    ),
                ),
                (
                    "filename",
                    models.CharField(help_text="Tên file gốc", max_length=255),
                ),
                ("file_size", models.IntegerField(help_text="Kích thước file (bytes)")),
                ("comment", models.TextField(blank=True, help_text="Ghi chú về file")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        help_text="Task chứa file này",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="tasks.task",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        help_text="Người upload file",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Task File",
                "verbose_name_plural": "Task Files",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
