# Generated by Django 5.0.1 on 2026-02-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Giá tiền cho task này', max_digits=10, null=True),
        ),
    ]
