# Generated by Django 5.0.1 on 2026-03-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0006_alter_task_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="stage",
            field=models.CharField(
                choices=[
                    ("planning", "Planning"),
                    ("design", "Design"),
                    ("development", "Development"),
                    ("review", "Review"),
                    ("testing", "Testing"),
                    ("completed", "Completed"),
                ],
                default="planning",
                help_text="Giai đoạn thực hiện task",
                max_length=20,
            ),
        ),
    ]
