# Generated by Django 5.0.1 on 2026-03-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0007_task_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="stage_progress",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Tiến độ từng giai đoạn {"planning": "not_started", "design": "not_started", ...}',
            ),
        ),
    ]
