# Generated by Django 5.0.1 on 2026-03-16 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_projectstage"),
        ("tasks", "0008_task_stage_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="project_stage",
            field=models.ForeignKey(
                blank=True,
                help_text="Stage từ project (ưu tiên hơn stage cũ)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="projects.projectstage",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="stage",
            field=models.CharField(
                choices=[
                    ("planning", "Planning"),
                    ("design", "Design"),
                    ("development", "Development"),
                    ("review", "Review"),
                    ("testing", "Testing"),
                    ("completed", "Completed"),
                ],
                default="planning",
                help_text="Giai đoạn thực hiện task (legacy)",
                max_length=20,
            ),
        ),
    ]
