# Generated by Django 5.0.1 on 2026-03-23 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_task_project_stage_alter_task_stage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('field_name', models.CharField(help_text='Tên trường bị thay đổi', max_length=100)),
                ('old_value', models.TextField(blank=True, help_text='Giá trị cũ', null=True)),
                ('new_value', models.TextField(blank=True, help_text='Giá trị mới', null=True)),
                ('change_note', models.TextField(blank=True, help_text='Ghi chú thêm về thay đổi')),
                ('changed_by', models.ForeignKey(help_text='Người thực hiện thay đổi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_changes', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(help_text='Task được thay đổi', on_delete=django.db.models.deletion.CASCADE, related_name='change_history', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Task Change History',
                'verbose_name_plural': 'Task Change Histories',
                'ordering': ['-changed_at'],
            },
        ),
    ]
