# Generated by Django 5.0.1 on 2026-02-03 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overall_status",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("needs_revision", "Needs Revision"),
                        ],
                        help_text="Kết quả review tổng thể",
                        max_length=20,
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, help_text="Nhận xét chung về task"),
                ),
                ("reviewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewer",
                    models.ForeignKey(
                        help_text="Người review (Manager/Admin)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        help_text="Task được review",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Review",
                "verbose_name_plural": "Task Reviews",
                "ordering": ["-reviewed_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewCriteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_met",
                    models.BooleanField(help_text="Đã đáp ứng quy tắc hay chưa"),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, help_text="Nhận xét cụ thể về quy tắc này"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "design_rule",
                    models.ForeignKey(
                        help_text="Quy tắc thiết kế được đánh giá",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.designrule",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        help_text="Review chứa criteria này",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria",
                        to="reviews.taskreview",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Criteria",
                "verbose_name_plural": "Review Criteria",
                "ordering": ["design_rule__order", "created_at"],
                "unique_together": {("review", "design_rule")},
            },
        ),
    ]
